version: "3"
services:
  efem-dapp:
    build: ./dapp
    environment:
      - REACT_APP_ENVIRONMENT=localhost
      - REACT_APP_NODE_ID=33
      - IPFS_PINNING_ENABLED=false
      - CROWDFUNDING_ADDRESS='0xC1007078659F3814607eB7883d6bfc3902212c86'
      - FEATHERS_CONNECTION='http://localhost:3030'
      - IPFS_GATEWAY='http://localhost:8080/ipfs/'
    volumes:
      - ./dapp/config/configuration.js:/usr/src/app/src/configuration.js
      - ${DAPP_PATH_SRC:-./dapp/app/src}:/usr/src/app/src
      - ${DAPP_PATH_ENV:-./dapp/app/.env}:/usr/src/app/.env
      - ${SMART_CONTRACT_PROJECT}:/usr/src/app/node_modules/@acdi/give4forests-crowdfunding-contract
    depends_on:
      - efem-rsk


  efem-feathers:
    build: ./feathers
    volumes:
      - ./feathers/config/default.json:/usr/src/app/config/default.json
      - ${FEATHERS_PATH_SRC:-./feathers/src}:/usr/src/app/src
      - ${FEATHERS_PATH_ENV:-./feathers/.env}:/usr/src/app/.env
    depends_on:
      - efem-rsk


  efem-ipfs:
    build: 
      context: ./ipfs


  efem-rsk:
    container_name: efem-rsk
    image: efem/rsk-regtest
    build: 
      context: ./rsk/regtest
      dockerfile: Dockerfile.RegTest
    ports:
      - "4444:4444"
      - "4445:4445"
      - "30305:30305"