version: "3"
services:
  efem-dapp:
    container_name: efem-dapp
    image: efem/dapp
    build: ./dapp
    volumes:
      - ./dapp/config/configuration.js:/usr/src/app/src/configuration.js
      - /home/mauricio/dev/project/acdi/efem/efem-crowdfunding-dapp/src:/usr/src/app/src
      - /home/mauricio/dev/project/acdi/efem/efem-aragon-apps/apps/crowdfunding:/usr/src/app/node_modules/@acdi/efem-crowdfunding
    ports:
      - "3010:3010"
    depends_on:
      - efem-rsk
      - efem-ipfs
      - efem-mongodb
      - efem-feathers

  efem-feathers:
    container_name: efem-feathers
    image: efem/feathers
    build: ./feathers
    volumes:
      - ./feathers/config/default.json:/usr/src/app/config/default.json
    ports:
      - "3030:3030"
    depends_on:
      - efem-rsk
      - efem-ipfs
      - efem-mongodb

  efem-rsk:
    container_name: efem-rsk
    image: efem/rsk-regtest
    build: 
      context: ./rsk
      dockerfile: Dockerfile.RegTest
    ports:
      - "4444:4444"
      - "4445:4445"
      - "30305:30305"
    restart: on-failure
    healthcheck:
      test: 
         - "CMD"
         - "curl"
         - "-s"
         - "-X"
         - "POST"
         - "-H"
         - " \"Content-Type: application/json\" "
         - "http://localhost:4444/"
         - "--data"
         - "'{\"jsonrpc\":\"2.0\",\"method\":\"eth_blockNumber\",\"params\":[],\"id\":1}'"
      interval: 30s
      retries: 1

  efem-ipfs:
    container_name: efem-ipfs
    image: efem/ipfs
    build: 
      context: ./ipfs
    volumes:
      - ipfs-data:/data/ipfs
      - ipfs-export:/export
    ports:
      - "4001:4001"     # Swarm tcp, should be exposed to the public
      - "4001:4001/udp" # Swarm tcp, should be exposed to the public
      - "5001:5001"     # Daemon API; must not be exposed publicly but to client services under you control
      - "8080:8080"     # Web Gateway

  efem-mongodb:
    container_name: efem-mongodb
    image: mongo:3.6.18
    expose:
      - "27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
  ipfs-data:
  ipfs-export:
