version: "3"
services:
  efem-dapp:
    ports:
      - "80:3010"
    environment:
      - REACT_APP_ENVIRONMENT=rsk_testnet
      - REACT_APP_NODE_CONNECTION_URL=https://public-node.testnet.rsk.co
      - REACT_APP_NODE_ID=31
      - REACT_APP_CROWDFUNDING_ADDRESS=0x8baf2c0afb7c4e8baa9890982669d73307706610
      - REACT_APP_FEATHERJS_CONNECTION_URL=http://x.x.x.x:yyyy
      - REACT_APP_IPFS_GATEWAY=http://x.x.x.x:yyyy/ipfs/
      - REACT_APP_IPFS_PINNING_ENABLED=true
    restart: always
  efem-feathers:
    ports:
      - "3030:3030"
    restart: always
  efem-ipfs:
    ports:
      - "4001:4001"     # Swarm tcp, should be exposed to the public
      - "4001:4001/udp" # Swarm tcp, should be exposed to the public
      - "5001:5001"     # Daemon API; must not be exposed publicly but to client services under you control
      - "8080:8080"     # Web Gateway
    restart: always
  