version: "3"
services:
  efem-dapp:
    ports:
      - "80:3010"
    environment:
      - REACT_APP_ENVIRONMENT=rsk_testnet
      - REACT_APP_NODE_ID=31
      - IPFS_PINNING_ENABLED=true
      - CROWDFUNDING_ADDRESS='0x8baf2c0afb7c4e8baa9890982669d73307706610'
      - FEATHERS_CONNECTION='http://x.x.x.x:yyyy'
      - IPFS_GATEWAY='http://x.x.x.x:yyyy/ipfs/'
      #TODO: Leer desde el .env las cosas que no deban ser publicas
    restart: always
  efem-feathers:
    ports:
      - "3030:3030"
    restart: always
  efem-ipfs:
    ports:
      - "4001:4001"     # Swarm tcp, should be exposed to the public
      - "4001:4001/udp" # Swarm tcp, should be exposed to the public
      - "5001:5001"     # Daemon API; must not be exposed publicly but to client services under you control
      - "8080:8080"     # Web Gateway
    restart: always
  