version: "3"
services:
  efem-dapp:
    ports:
      - "80:3010"
    environment:
      - REACT_APP_ENVIRONMENT=rsk_testnet
      - REACT_APP_NODE_CONNECTION_URL=https://public-node.testnet.rsk.co
      - REACT_APP_NODE_ID=31
      - REACT_APP_CROWDFUNDING_ADDRESS=0x49733dF856718066Ca3eFA3a55B1Fa00c74C13de
      - REACT_APP_EXCHANGE_RATE_PROVIDER_ADDRESS=0x0Aa058aD63E36bC2f98806f2D638353AE89C3634
      - REACT_APP_TOKEN_DOC_ADDRESS=0x05A55E87d40572ea0F9e9D37079FB9cA11bdCc67
      - REACT_APP_FEATHERJS_CONNECTION_URL=http://34.122.49.162:3030/
      - REACT_APP_IPFS_GATEWAY=http://34.122.49.162:8080/ipfs/
      - REACT_APP_IPFS_PINNING_ENABLED=true
    restart: always
  efem-feathers:
    ports:
      - "3030:3030"
    restart: always
    volumes:
      - ./feathers/config/default.json:/usr/src/app/config/default.json
      - ./feathers/config/.env:/usr/src/app/.env
  efem-ipfs:
    ports:
      - "4001:4001"     # Swarm tcp, should be exposed to the public
      - "4001:4001/udp" # Swarm tcp, should be exposed to the public
      - "5001:5001"     # Daemon API; must not be exposed publicly but to client services under you control
      - "8080:8080"     # Web Gateway
    restart: always
  
